"""
Seed data: realistic Russian food suppliers for demo / initial load.
Run via: python -m scrapers.seed_data
"""
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.supplier import Category, Supplier

CATEGORIES = [
    {"name": "Молочная продукция", "slug": "dairy"},
    {"name": "Мясо и птица", "slug": "meat"},
    {"name": "Рыба и морепродукты", "slug": "fish"},
    {"name": "Овощи и фрукты", "slug": "produce"},
    {"name": "Бакалея", "slug": "grocery"},
    {"name": "Напитки", "slug": "beverages"},
    {"name": "Специи и приправы", "slug": "spices"},
    {"name": "Упаковка", "slug": "packaging"},
    {"name": "Хлеб и выпечка", "slug": "bakery"},
    {"name": "Кондитерские изделия", "slug": "confectionery"},
    {"name": "Замороженная продукция", "slug": "frozen"},
    {"name": "Масло и жиры", "slug": "oils"},
]

SUPPLIERS = [
    # ─── Молочная продукция ──────────────────────────────────────────────────
    {
        "name": "ООО «Молочный Двор»",
        "category_slug": "dairy",
        "description": "Оптовые поставки молочной продукции: молоко 3,2%, сметана, творог, кефир, ряженка. Собственная ферма и производство в Подмосковье. Работаем с HoReCa и розничными сетями.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (495) 123-45-67",
        "email": "opt@molochny-dvor.ru",
        "website": "molochny-dvor.ru",
        "min_order_amount": 50000,
        "min_order_unit": "руб",
        "price_range_description": "от 55 руб/л (молоко), от 120 руб/кг (сметана)",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "Ветеринарное свидетельство", "ТР ТС 033/2013"],
        "delivery_conditions": "Бесплатная доставка при заказе от 50 000 руб по Москве и МО. Собственный рефрижератор.",
        "delivery_regions": ["Москва", "Московская область"],
        "source_platform": "seed",
    },
    {
        "name": "АО «Вологодское Масло»",
        "category_slug": "dairy",
        "description": "Производитель традиционного вологодского масла, сыров и молочных консервов. Поставляем оптом в регионы РФ.",
        "city": "Вологда",
        "region": "Вологодская область",
        "phone": "+7 (8172) 55-01-23",
        "email": "sales@vologda-maslo.ru",
        "website": "vologda-maslo.ru",
        "min_order_amount": 100000,
        "min_order_unit": "руб",
        "price_range_description": "Масло от 580 руб/кг, сыры от 350 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ Р 52253-2004", "ТР ТС 033/2013", "ISO 22000"],
        "delivery_conditions": "Доставка ТК СДЭК, ПЭК, собственным транспортом по Северо-Западу.",
        "delivery_regions": ["Вологодская область", "Санкт-Петербург", "Москва", "Северо-Запад"],
        "source_platform": "seed",
    },
    {
        "name": "ИП Петрова — «Фермерская Лавка»",
        "category_slug": "dairy",
        "description": "Небольшая фермерская молочня. Козье молоко, домашний сыр, творог без консервантов. Идеально для ресторанов и фермерских магазинов.",
        "city": "Пушкино",
        "region": "Московская область",
        "phone": "+7 (916) 234-56-78",
        "email": "ferma@petrova.farm",
        "website": "",
        "min_order_amount": 5000,
        "min_order_unit": "руб",
        "price_range_description": "Козье молоко 150 руб/л, творог 300 руб/кг",
        "has_certificates": False,
        "certificate_types": [],
        "delivery_conditions": "Самовывоз или доставка по Москве (договорная).",
        "delivery_regions": ["Москва", "Московская область"],
        "source_platform": "seed",
        "notes": "Работает только по предзаказу, количество ограничено",
    },
    {
        "name": "ООО «Кубань-Молоко»",
        "category_slug": "dairy",
        "description": "Крупный производитель пастеризованного молока, кефира, йогуртов и сыворотки на Юге России. Мощность производства — 200 т/сутки.",
        "city": "Краснодар",
        "region": "Краснодарский край",
        "phone": "+7 (861) 290-00-10",
        "email": "b2b@kuban-moloko.ru",
        "website": "kuban-moloko.ru",
        "min_order_amount": 200000,
        "min_order_unit": "руб",
        "price_range_description": "Молоко от 48 руб/л, йогурт от 85 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ТР ТС 033/2013", "HACCP"],
        "delivery_conditions": "Доставка по ЮФО и СКФО. Доставка в Москву от 500 000 руб.",
        "delivery_regions": ["Краснодарский край", "Ростовская область", "Ставропольский край", "Москва"],
        "source_platform": "seed",
    },
    # ─── Мясо и птица ────────────────────────────────────────────────────────
    {
        "name": "ООО «Мясной Комбинат Черкизово»",
        "category_slug": "meat",
        "description": "Одна из крупнейших мясоперерабатывающих компаний России. Колбасы, сосиски, деликатесы, полуфабрикаты. Оптовые поставки по всей РФ.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (495) 785-00-00",
        "email": "opt@cherkizovo.ru",
        "website": "cherkizovo.ru",
        "min_order_amount": 500000,
        "min_order_unit": "руб",
        "price_range_description": "Колбасы от 220 руб/кг, полуфабрикаты от 160 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ТР ТС 034/2013", "HACCP", "Халяль"],
        "delivery_conditions": "Доставка по всей России. Собственный автопарк рефрижераторов.",
        "delivery_regions": ["Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "КФХ «Иваново Подворье»",
        "category_slug": "meat",
        "description": "Фермерская говядина и свинина. Скот выращен на натуральных кормах без антибиотиков. Поставляем тушами, полутушами и отрубами.",
        "city": "Иваново",
        "region": "Ивановская область",
        "phone": "+7 (910) 678-90-12",
        "email": "ivanov@podvorie.farm",
        "website": "",
        "min_order_amount": 30000,
        "min_order_unit": "руб",
        "price_range_description": "Говядина от 450 руб/кг, свинина от 350 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Ветеринарное свидетельство"],
        "delivery_conditions": "Доставка по Ивановской, Ярославской, Костромской областям.",
        "delivery_regions": ["Ивановская область", "Ярославская область", "Москва"],
        "source_platform": "seed",
        "notes": "Возможна поставка «на убой» по договорённости",
    },
    {
        "name": "ООО «Птицефабрика Сибирская»",
        "category_slug": "meat",
        "description": "Производство охлаждённой и замороженной курицы, индейки, куриного яйца. Мощность 80 000 голов в сутки. Сертифицировано по HACCP.",
        "city": "Новосибирск",
        "region": "Новосибирская область",
        "phone": "+7 (383) 350-40-00",
        "email": "opt@sib-ptitsa.ru",
        "website": "sib-ptitsa.ru",
        "min_order_amount": 150000,
        "min_order_unit": "руб",
        "price_range_description": "Тушка куриная от 130 руб/кг, филе от 220 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "HACCP", "ТР ТС 021/2011"],
        "delivery_conditions": "Доставка по Сибири и Уралу. Экспорт по запросу.",
        "delivery_regions": ["Новосибирская область", "Кемеровская область", "Омская область", "Красноярский край"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «Ростов Мит»",
        "category_slug": "meat",
        "description": "Поставщик свинины, говядины, субпродуктов. Работаем с ресторанами, столовыми, магазинами. Гибкая нарезка под заказ.",
        "city": "Ростов-на-Дону",
        "region": "Ростовская область",
        "phone": "+7 (863) 200-30-40",
        "email": "zakaz@rostov-meat.ru",
        "website": "rostov-meat.ru",
        "min_order_amount": 20000,
        "min_order_unit": "руб",
        "price_range_description": "Свинина от 280 руб/кг, говядина от 380 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Ветеринарное свидетельство", "ГОСТ"],
        "delivery_conditions": "Доставка по Ростовской области и Краснодарскому краю.",
        "delivery_regions": ["Ростовская область", "Краснодарский край"],
        "source_platform": "seed",
    },
    # ─── Рыба и морепродукты ─────────────────────────────────────────────────
    {
        "name": "ООО «Мурманский Берег»",
        "category_slug": "fish",
        "description": "Рыба и морепродукты с Баренцева моря: треска, пикша, палтус, краб, гребешок. Свежемороженая и охлаждённая. Оптовые поставки.",
        "city": "Мурманск",
        "region": "Мурманская область",
        "phone": "+7 (8152) 45-67-89",
        "email": "fish@murman-bereg.ru",
        "website": "murman-bereg.ru",
        "min_order_amount": 80000,
        "min_order_unit": "руб",
        "price_range_description": "Треска от 200 руб/кг, краб от 1 500 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ВСД", "MSC"],
        "delivery_conditions": "Поставки рефрижераторами по всей России. Экспорт.",
        "delivery_regions": ["Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «Дальморепродукт»",
        "category_slug": "fish",
        "description": "Дальневосточная рыба и морепродукты: горбуша, кета, минтай, кальмар, морской ёж. Прямые поставки с флота.",
        "city": "Владивосток",
        "region": "Приморский край",
        "phone": "+7 (4232) 56-78-90",
        "email": "opt@dalmorep.ru",
        "website": "dalmorep.ru",
        "min_order_amount": 200000,
        "min_order_unit": "руб",
        "price_range_description": "Горбуша от 170 руб/кг, кальмар от 250 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ВСД", "ТР ТС 040/2016"],
        "delivery_conditions": "Ж/д и авиадоставка по РФ. Рефрижераторные контейнеры.",
        "delivery_regions": ["Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «АквафермаСевер»",
        "category_slug": "fish",
        "description": "Форель и сёмга аквакультуры из Карелии. Живая, охлаждённая, копчёная. Работаем с ресторанами и ритейлом.",
        "city": "Петрозаводск",
        "region": "Республика Карелия",
        "phone": "+7 (8142) 78-90-12",
        "email": "sales@akvaferma-sever.ru",
        "website": "akvaferma-sever.ru",
        "min_order_amount": 50000,
        "min_order_unit": "руб",
        "price_range_description": "Форель охл. от 480 руб/кг, сёмга от 700 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ВСД", "ГОСТ", "GlobalG.A.P."],
        "delivery_conditions": "Доставка по Северо-Западу. В Москву — 2 раза в неделю.",
        "delivery_regions": ["Карелия", "Санкт-Петербург", "Москва", "Северо-Запад"],
        "source_platform": "seed",
    },
    # ─── Овощи и фрукты ──────────────────────────────────────────────────────
    {
        "name": "ООО «Агрокомплекс Юг»",
        "category_slug": "produce",
        "description": "Крупнейший поставщик тепличных овощей: помидоры, огурцы, перец, зелень. Собственные теплицы 150 га в Краснодарском крае.",
        "city": "Краснодар",
        "region": "Краснодарский край",
        "phone": "+7 (861) 256-00-11",
        "email": "opt@agrokomplex-yug.ru",
        "website": "agrokomplex-yug.ru",
        "min_order_amount": 100000,
        "min_order_unit": "руб",
        "price_range_description": "Томаты от 65 руб/кг, огурцы от 55 руб/кг",
        "has_certificates": True,
        "certificate_types": ["GlobalG.A.P.", "Органик", "ГОСТ"],
        "delivery_conditions": "Поставки по ЮФО, в Москву и СПб от 500 кг.",
        "delivery_regions": ["Краснодарский край", "Москва", "Санкт-Петербург", "ЮФО"],
        "source_platform": "seed",
    },
    {
        "name": "ИП Саакян — Фрукты из Армении",
        "category_slug": "produce",
        "description": "Прямые поставки сезонных фруктов из Армении: абрикосы, персики, гранат, виноград. Импорт без посредников.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (909) 890-12-34",
        "email": "saakyan.fruits@mail.ru",
        "website": "",
        "min_order_amount": 15000,
        "min_order_unit": "руб",
        "price_range_description": "Абрикосы от 120 руб/кг, гранат от 180 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Фитосанитарный сертификат"],
        "delivery_conditions": "Доставка по Москве. Самовывоз с Дорогомиловского рынка.",
        "delivery_regions": ["Москва"],
        "source_platform": "seed",
        "notes": "Сезонность: апрель–октябрь",
    },
    {
        "name": "ООО «ВолгаОвощ»",
        "category_slug": "produce",
        "description": "Оптовые поставки картофеля, лука, моркови, свёклы и капусты. Собственные хранилища ёмкостью 10 000 т.",
        "city": "Волгоград",
        "region": "Волгоградская область",
        "phone": "+7 (8442) 34-56-78",
        "email": "zakaz@volga-ovosh.ru",
        "website": "volga-ovosh.ru",
        "min_order_amount": 30000,
        "min_order_unit": "руб",
        "price_range_description": "Картофель от 18 руб/кг, лук от 22 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Фитосанитарный сертификат", "Декларация соответствия"],
        "delivery_conditions": "Доставка по ЦФО и ЮФО. Объём от 5 т.",
        "delivery_regions": ["Волгоградская область", "Ростовская область", "Москва", "ЦФО"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «ГринФарм Сибирь»",
        "category_slug": "produce",
        "description": "Зелень и микрозелень круглогодично: укроп, петрушка, кинза, базилик, шпинат, рукола. Гидропонные теплицы.",
        "city": "Новосибирск",
        "region": "Новосибирская область",
        "phone": "+7 (383) 277-88-99",
        "email": "sales@greenfarm-sib.ru",
        "website": "greenfarm-sib.ru",
        "min_order_amount": 5000,
        "min_order_unit": "руб",
        "price_range_description": "Зелень пучок от 45 руб, микрозелень от 500 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Органик", "Декларация соответствия"],
        "delivery_conditions": "Доставка по Новосибирску ежедневно. Поставки в Екатеринбург.",
        "delivery_regions": ["Новосибирская область", "Кемеровская область", "Омская область"],
        "source_platform": "seed",
    },
    # ─── Бакалея ─────────────────────────────────────────────────────────────
    {
        "name": "ООО «МукоМол»",
        "category_slug": "grocery",
        "description": "Производство и оптовая продажа муки: пшеничная в/с, 1с, 2с, ржаная, цельнозерновая, спельтовая. Собственный мельзавод.",
        "city": "Воронеж",
        "region": "Воронежская область",
        "phone": "+7 (473) 234-11-22",
        "email": "muka@mukomol-vrn.ru",
        "website": "mukomol-vrn.ru",
        "min_order_amount": 50000,
        "min_order_unit": "руб",
        "price_range_description": "Мука пш. в/с от 28 руб/кг, цельнозерновая от 55 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ISO 9001", "Органик (спельта)"],
        "delivery_conditions": "Доставка по ЦФО. Отгрузка от 1 т мешками по 25/50 кг.",
        "delivery_regions": ["Воронежская область", "Москва", "Тульская область", "ЦФО"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «СибирьРис»",
        "category_slug": "grocery",
        "description": "Оптовая торговля крупами: рис, гречка, пшено, перловка, булгур, киноа. Собственный упаковочный цех.",
        "city": "Новосибирск",
        "region": "Новосибирская область",
        "phone": "+7 (383) 344-55-66",
        "email": "opt@sib-ris.ru",
        "website": "sib-ris.ru",
        "min_order_amount": 100000,
        "min_order_unit": "руб",
        "price_range_description": "Рис длиннозёрный от 65 руб/кг, гречка от 45 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ISO 22000"],
        "delivery_conditions": "Доставка по Сибири, Уралу. Ж/д отгрузка по всей РФ.",
        "delivery_regions": ["Новосибирская область", "Омская область", "Красноярский край", "Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «Масло-Опт»",
        "category_slug": "oils",
        "description": "Подсолнечное масло рафинированное и нерафинированное, оливковое extra virgin, масло виноградной косточки. Оптом от 5 л.",
        "city": "Екатеринбург",
        "region": "Свердловская область",
        "phone": "+7 (343) 200-10-20",
        "email": "sales@maslo-opt.ru",
        "website": "maslo-opt.ru",
        "min_order_amount": 30000,
        "min_order_unit": "руб",
        "price_range_description": "Подсолнечное от 95 руб/л, оливковое от 580 руб/л",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "Декларация соответствия"],
        "delivery_conditions": "Доставка по Уралу и Сибири. Отгрузка от 100 л.",
        "delivery_regions": ["Свердловская область", "Тюменская область", "Пермский край", "Урал"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «Органик Лайн»",
        "category_slug": "grocery",
        "description": "Органические продукты: мука, крупы, сухофрукты, бобовые, семена. Сертификат органического производства ЕС и РФ.",
        "city": "Санкт-Петербург",
        "region": "Санкт-Петербург",
        "phone": "+7 (812) 612-34-56",
        "email": "organic@organic-line.ru",
        "website": "organic-line.ru",
        "min_order_amount": 20000,
        "min_order_unit": "руб",
        "price_range_description": "от 80 руб/кг (крупы), от 150 руб/кг (сухофрукты)",
        "has_certificates": True,
        "certificate_types": ["Органик EU", "Органик РФ", "ISO 22000"],
        "delivery_conditions": "Доставка по России ТК. Бесплатная по СПб от 20 000 руб.",
        "delivery_regions": ["Санкт-Петербург", "Москва", "Вся Россия"],
        "source_platform": "seed",
    },
    # ─── Напитки ─────────────────────────────────────────────────────────────
    {
        "name": "ООО «АкваСтандарт»",
        "category_slug": "beverages",
        "description": "Питьевая вода в бутылках 0,33 / 0,5 / 1,5 / 5 л. Газированная и негазированная. Поставки для HoReCa, офисов, ритейла.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (495) 789-00-11",
        "email": "opt@akvastandart.ru",
        "website": "akvastandart.ru",
        "min_order_amount": 25000,
        "min_order_unit": "руб",
        "price_range_description": "0,5 л от 9 руб/бут, 5 л от 75 руб/бут",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "Санитарно-эпидемиологическое заключение"],
        "delivery_conditions": "Доставка по Москве и МО. Возврат тары.",
        "delivery_regions": ["Москва", "Московская область"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «Фруктовый Сок»",
        "category_slug": "beverages",
        "description": "Прямые соки и нектары в ассортименте: яблоко, апельсин, мультифрукт, томат, морковь. Упаковка 1л Tetra Pak, 3л bag-in-box.",
        "city": "Липецк",
        "region": "Липецкая область",
        "phone": "+7 (4742) 45-67-00",
        "email": "sales@fruktoviy-sok.ru",
        "website": "fruktoviy-sok.ru",
        "min_order_amount": 75000,
        "min_order_unit": "руб",
        "price_range_description": "Сок 1 л от 45 руб, bag-in-box 3 л от 110 руб",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ТР ТС 023/2011", "ISO 22000"],
        "delivery_conditions": "Доставка по ЦФО. Экспорт в СНГ.",
        "delivery_regions": ["Липецкая область", "Москва", "ЦФО", "Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «Кофе Трейд»",
        "category_slug": "beverages",
        "description": "Обжарщик кофе и импортёр чая. Моносорта и купажи в зерне и молотом. Оптовые поставки кафе, ресторанам, офисам.",
        "city": "Москва",
        "region": "Москва",
        "phone": "+7 (495) 600-90-80",
        "email": "trade@coffee-trade.ru",
        "website": "coffee-trade.ru",
        "min_order_amount": 10000,
        "min_order_unit": "руб",
        "price_range_description": "Кофе в зерне от 700 руб/кг, чай от 400 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Декларация соответствия", "Сертификат происхождения"],
        "delivery_conditions": "Бесплатная доставка по Москве от 5 000 руб. Почта РФ, СДЭК.",
        "delivery_regions": ["Москва", "Вся Россия"],
        "source_platform": "seed",
    },
    # ─── Специи и приправы ───────────────────────────────────────────────────
    {
        "name": "ООО «Пряный Мир»",
        "category_slug": "spices",
        "description": "Оптовые поставки специй и пряностей: перец, паприка, куркума, кориандр, зира, сушёные травы. Фасовка под СТМ.",
        "city": "Москва",
        "region": "Москва",
        "phone": "+7 (495) 411-22-33",
        "email": "opt@pryaniy-mir.ru",
        "website": "pryaniy-mir.ru",
        "min_order_amount": 15000,
        "min_order_unit": "руб",
        "price_range_description": "Перец чёрный от 300 руб/кг, куркума от 250 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Декларация соответствия", "Фитосанитарный сертификат"],
        "delivery_conditions": "Доставка по России ТК СДЭК, Деловые Линии.",
        "delivery_regions": ["Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «СпецАзия»",
        "category_slug": "spices",
        "description": "Импорт и оптовая торговля азиатскими специями: тамаринд, карри, гарам масала, чили, лемонграсс. Прямые контракты с Индией и Вьетнамом.",
        "city": "Санкт-Петербург",
        "region": "Санкт-Петербург",
        "phone": "+7 (812) 385-10-20",
        "email": "asia@specazia.ru",
        "website": "specazia.ru",
        "min_order_amount": 20000,
        "min_order_unit": "руб",
        "price_range_description": "Карри от 180 руб/кг, гарам масала от 250 руб/кг",
        "has_certificates": True,
        "certificate_types": ["Фитосанитарный сертификат", "Сертификат происхождения"],
        "delivery_conditions": "Доставка по России. Минимальная отгрузка — 5 кг/позиция.",
        "delivery_regions": ["Санкт-Петербург", "Москва", "Вся Россия"],
        "source_platform": "seed",
    },
    # ─── Упаковка ─────────────────────────────────────────────────────────────
    {
        "name": "ООО «ПакТрейд»",
        "category_slug": "packaging",
        "description": "Производство и оптовые поставки упаковки для пищевых продуктов: пластиковые контейнеры, ПЭТ-лотки, крышки, плёнка. Печать логотипа под СТМ.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (495) 776-00-22",
        "email": "pack@paktrade.ru",
        "website": "paktrade.ru",
        "min_order_amount": 30000,
        "min_order_unit": "руб",
        "price_range_description": "Контейнеры от 4 руб/шт, лотки от 6 руб/шт",
        "has_certificates": True,
        "certificate_types": ["ТР ТС 005/2011", "Декларация соответствия"],
        "delivery_conditions": "Доставка по Москве и МО. ТК по России.",
        "delivery_regions": ["Москва", "Московская область", "Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «ЭкоТара»",
        "category_slug": "packaging",
        "description": "Экологичная упаковка: крафт-пакеты, картонные коробки, деревянные поддоны, биоразлагаемые контейнеры. FSC-сертификация.",
        "city": "Екатеринбург",
        "region": "Свердловская область",
        "phone": "+7 (343) 380-10-10",
        "email": "eco@ekotara.ru",
        "website": "ekotara.ru",
        "min_order_amount": 20000,
        "min_order_unit": "руб",
        "price_range_description": "Крафт-пакеты от 3 руб/шт, коробки от 15 руб/шт",
        "has_certificates": True,
        "certificate_types": ["FSC", "ТР ТС 005/2011"],
        "delivery_conditions": "Доставка по Уралу. ТК по России.",
        "delivery_regions": ["Свердловская область", "Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «СтеклоПак»",
        "category_slug": "packaging",
        "description": "Стеклянная тара: банки, бутылки, флаконы. Оптовые партии от 100 шт. Возможна гравировка и нанесение логотипа.",
        "city": "Нижний Новгород",
        "region": "Нижегородская область",
        "phone": "+7 (831) 420-33-44",
        "email": "glass@steklopak.ru",
        "website": "steklopak.ru",
        "min_order_amount": 50000,
        "min_order_unit": "руб",
        "price_range_description": "Банки 0,5 л от 18 руб/шт, бутылки от 22 руб/шт",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ТР ТС 005/2011"],
        "delivery_conditions": "Доставка по ПФО. ТК по России.",
        "delivery_regions": ["Нижегородская область", "Москва", "Вся Россия"],
        "source_platform": "seed",
    },
    # ─── Хлеб и выпечка ──────────────────────────────────────────────────────
    {
        "name": "ООО «Хлебный Дом»",
        "category_slug": "bakery",
        "description": "Производство замороженных полуфабрикатов выпечки: багеты, круассаны, пирожки, слойки. Технология «выпекай сам» для HoReCa.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (495) 680-70-80",
        "email": "bakery@hlebny-dom.ru",
        "website": "hlebny-dom.ru",
        "min_order_amount": 40000,
        "min_order_unit": "руб",
        "price_range_description": "Круассаны от 45 руб/шт, багеты от 35 руб/шт",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "HACCP", "Декларация соответствия"],
        "delivery_conditions": "Доставка рефрижераторами по Москве и МО еженедельно.",
        "delivery_regions": ["Москва", "Московская область"],
        "source_platform": "seed",
    },
    {
        "name": "ИП Кузнецов — Ремесленный хлеб",
        "category_slug": "bakery",
        "description": "Артизанский хлеб на закваске: ржаной, пшенично-ржаной, чиабатта, фокачча. Для ресторанов и фермерских рынков.",
        "city": "Санкт-Петербург",
        "region": "Санкт-Петербург",
        "phone": "+7 (921) 567-89-01",
        "email": "kuznetsov.bread@gmail.com",
        "website": "",
        "min_order_amount": 5000,
        "min_order_unit": "руб",
        "price_range_description": "Хлеб от 150 руб/буханка",
        "has_certificates": False,
        "certificate_types": [],
        "delivery_conditions": "Доставка по СПб 3 раза в неделю.",
        "delivery_regions": ["Санкт-Петербург"],
        "source_platform": "seed",
        "notes": "Ручное производство, ограниченные партии",
    },
    # ─── Кондитерские изделия ────────────────────────────────────────────────
    {
        "name": "ООО «Сладкий Мир»",
        "category_slug": "confectionery",
        "description": "Шоколад, конфеты, карамель, драже оптом. Под СТМ: разработка рецептуры, дизайн упаковки. Мощность 500 т/месяц.",
        "city": "Москва",
        "region": "Московская область",
        "phone": "+7 (495) 515-20-30",
        "email": "candy@sladkiy-mir.ru",
        "website": "sladkiy-mir.ru",
        "min_order_amount": 200000,
        "min_order_unit": "руб",
        "price_range_description": "Шоколад от 350 руб/кг, карамель от 180 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ISO 22000", "Халяль"],
        "delivery_conditions": "Доставка по России. Экспорт в СНГ.",
        "delivery_regions": ["Вся Россия"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «ПряникоФ»",
        "category_slug": "confectionery",
        "description": "Производство пряников, печенья и тульских пряников под СТМ. Брендирование упаковки. Корпоративные заказы.",
        "city": "Тула",
        "region": "Тульская область",
        "phone": "+7 (4872) 33-44-55",
        "email": "order@pryanikof.ru",
        "website": "pryanikof.ru",
        "min_order_amount": 25000,
        "min_order_unit": "руб",
        "price_range_description": "Пряники от 200 руб/кг, печенье от 170 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "Декларация соответствия"],
        "delivery_conditions": "Доставка по ЦФО. ТК по России.",
        "delivery_regions": ["Тульская область", "Москва", "ЦФО", "Вся Россия"],
        "source_platform": "seed",
    },
    # ─── Замороженная продукция ───────────────────────────────────────────────
    {
        "name": "ООО «АйсФуд»",
        "category_slug": "frozen",
        "description": "Замороженные овощи, ягоды, грибы: брокколи, шпинат, клубника, черника, шампиньоны. IQF-заморозка. Без консервантов.",
        "city": "Краснодар",
        "region": "Краснодарский край",
        "phone": "+7 (861) 300-55-66",
        "email": "opt@icefood-krd.ru",
        "website": "icefood-krd.ru",
        "min_order_amount": 60000,
        "min_order_unit": "руб",
        "price_range_description": "Клубника от 200 руб/кг, брокколи от 120 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "ТР ТС 021/2011", "ISO 22000"],
        "delivery_conditions": "Доставка рефрижераторами по ЮФО и ЦФО.",
        "delivery_regions": ["Краснодарский край", "Москва", "ЮФО", "ЦФО"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «ПельменьОпт»",
        "category_slug": "frozen",
        "description": "Замороженные полуфабрикаты: пельмени, вареники, хинкали, манты, блины. Производство в Нижнем Новгороде. Рецептуры под заказ.",
        "city": "Нижний Новгород",
        "region": "Нижегородская область",
        "phone": "+7 (831) 210-40-50",
        "email": "pelmeni@opt-nn.ru",
        "website": "pelmen-opt.ru",
        "min_order_amount": 50000,
        "min_order_unit": "руб",
        "price_range_description": "Пельмени от 200 руб/кг, вареники от 180 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ГОСТ", "HACCP"],
        "delivery_conditions": "Доставка рефрижераторами по ПФО и ЦФО.",
        "delivery_regions": ["Нижегородская область", "Москва", "Казань", "ПФО"],
        "source_platform": "seed",
    },
    {
        "name": "ООО «УралМорепродукт»",
        "category_slug": "frozen",
        "description": "Оптовая торговля замороженными морепродуктами: креветки, мидии, кальмар, осьминог. Поставки с Дальнего Востока и импорт.",
        "city": "Екатеринбург",
        "region": "Свердловская область",
        "phone": "+7 (343) 345-67-89",
        "email": "sea@ural-seafood.ru",
        "website": "ural-seafood.ru",
        "min_order_amount": 80000,
        "min_order_unit": "руб",
        "price_range_description": "Креветки от 500 руб/кг, мидии от 280 руб/кг",
        "has_certificates": True,
        "certificate_types": ["ВСД", "ГОСТ"],
        "delivery_conditions": "Доставка по Уралу и Сибири рефрижераторами.",
        "delivery_regions": ["Свердловская область", "Тюменская область", "Челябинская область", "Урал"],
        "source_platform": "seed",
    },
]


async def load_seed_data(db_session: AsyncSession) -> None:
    """Populate DB with categories and suppliers if tables are empty."""
    count = await db_session.scalar(select(func.count()).select_from(Category))
    if count and count > 0:
        return

    cat_map: dict[str, Category] = {}
    for cat in CATEGORIES:
        obj = Category(name=cat["name"], slug=cat["slug"])
        db_session.add(obj)
        cat_map[cat["slug"]] = obj
    await db_session.flush()

    for s in SUPPLIERS:
        cat_slug = s["category_slug"]
        fields = {k: v for k, v in s.items() if k != "category_slug"}
        supplier = Supplier(
            **fields,
            category=cat_map.get(cat_slug),
            scraped_at=None,
        )
        db_session.add(supplier)

    await db_session.commit()
